---
- hosts: nodes
  gather_facts: no

  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
      changed_when: False
    - setup:

  tasks:    
  - name: Install node, npm, pip and build-essential
    apt:
      name: "{{ item }}"
      state: present
    become: yes
    with_items:
      - nodejs
      - npm
      - build-essential
      - python-pip
      - python3-pip

  - name: Create job for checkbox.io
    jenkins_job:
      config: "{{ lookup('file','checkbox_config.xml')}}"
      name: checkbox